# Generated by Django 2.1 on 2018-10-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontosturisticos',
            options={'verbose_name_plural': 'pontos turisticos'},
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco'),
        ),
    ]
