# Generated by Django 2.1 on 2018-09-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name_plural': 'comentarios'},
        ),
    ]
