# Generated by Django 2.1 on 2018-09-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracoes',
            options={'verbose_name_plural': 'Atrações'},
        ),
        migrations.AlterField(
            model_name='atracoes',
            name='horario',
            field=models.TextField(),
        ),
    ]
